# Generated by Django 3.1.1 on 2020-09-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attached',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
