# Generated by Django 3.1.1 on 2020-09-20 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_auto_20200905_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attached',
        ),
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
