# Generated by Django 3.1.1 on 2020-09-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_auto_20200920_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
    ]
