# Generated by Django 3.1.1 on 2020-09-21 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_auto_20200921_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, unique=True),
        ),
    ]
