# Generated by Django 3.1.1 on 2020-10-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_auto_20201003_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default='0AF75C62', unique=True),
        ),
    ]
