# Generated by Django 3.1.2 on 2020-10-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_auto_20201008_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_comments', to='knowledge.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='F6F6D130', max_length=8, unique=True),
        ),
    ]
