# Generated by Django 3.1.2 on 2020-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0017_auto_20201008_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='C40C4878', max_length=8, unique=True),
        ),
    ]
