# Generated by Django 3.1.2 on 2020-10-25 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_auto_20201008_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='6D5175AC', max_length=8, unique=True),
        ),
    ]
