# Generated by Django 3.1.2 on 2020-11-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0019_auto_20201025_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='7553F0D1', max_length=8, unique=True),
        ),
    ]
