# Generated by Django 3.1.2 on 2020-11-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0021_auto_20201106_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='knowledge.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='750C01A5', max_length=8, unique=True),
        ),
    ]
