# Generated by Django 3.1.2 on 2020-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0023_auto_20201114_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='DF71D0EE1', max_length=9, unique=True),
        ),
    ]
