# Generated by Django 3.1.2 on 2020-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0025_auto_20201115_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='69C5FFD36', max_length=9, unique=True),
        ),
    ]
