# Generated by Django 3.1.2 on 2020-11-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0027_auto_20201115_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='83C40E4DD', max_length=9, unique=True),
        ),
    ]
