# Generated by Django 3.1.2 on 2020-11-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0031_auto_20201116_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='85ADEC424', max_length=9, unique=True),
        ),
    ]
