# Generated by Django 3.1.2 on 2020-11-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0032_auto_20201116_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='description',
            field=models.CharField(default='For all things related to technology', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='166895AC0', max_length=9, unique=True),
        ),
    ]
