# Generated by Django 3.1.4 on 2020-12-14 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0034_auto_20201120_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='hub',
            name='members',
            field=models.ManyToManyField(related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hub',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='865AA24B8', max_length=9, unique=True),
        ),
    ]
