# Generated by Django 3.1.4 on 2020-12-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0036_auto_20201223_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='hub',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_hubs', to='knowledge.hub'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='', max_length=9, unique=True),
        ),
    ]
