name: Run tests
on: [push]
jobs:
    django:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run migrations
              env:
                  SECRET_KEY: 02963a29894ceaf3fd4d34afdd58927ab5244c58612cb5ca19
              run: python manage.py migrate
            - name: Run tests
              run: |
                  python manage.py test

    react:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend

        steps:
            - uses: actions/checkout@v2
            - uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install
            - uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: test
