name: Run tests
on: [push]
jobs:
    django:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run migrations
              env:
                  SECRET_KEY: 02963a29894ceaf3fd4d34afdd58927ab5244c58612cb5ca19
              run: python manage.py migrate
            - name: Run tests
              run: |
                  python manage.py test

    react:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn install

            - name: Run the tests
              run: yarn test --verbose --maxWorkers=2
